name: Publish site to gh-pages
on:
  push:
    branches:
      - main 
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4.2.2
      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
        - name: Checkout main
          uses: actions/checkout@v4.2.2
        - name: Build & Deploy
          uses: shalzz/zola-deploy-action@v0.19.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
